### ISSUE TITLE
Enable Github Pages

### ISSUE THREAD

**Issue by ZeevoX** [harens/ThePonyInformationGuide#1]
You could enable [Github Pages](https://pages.github.com/) generation in [this repository's settings.](https://github.com/harens/ThePonyInformationGuide/settings)

Then you wouldn't have to rely on codepen for hosting and you could use Github instead!

**Comment by harens** [comment]
Great suggestion @ZeevoX !
I am just testing some things out, and I will be sure to implement your suggestion soon

**Comment by harens** [comment]
Great news!

The Pony Information Guide is now fully integrated with GitHub Pages. Find it [here](https://harens.github.io/ThePonyInformationGuide/)
Many thanks for the suggestion @ZeevoX
